### ISSUE TITLE
Load TMDb API key from config file

### ISSUE THREAD

**Issue by simon-andrews** [simon-andrews/movieman2#9]
Right now MM2 can only load a TMDb API key from the environment variable `MM2_TMDB_API_KEY`. There should be some to load the key from a config file. The config file should be in a proper data serialization format in case other settings might be loaded from it in the future. I'm liking JSON for this just because that would mean avoiding additional dependencies even though it isn't as human-readable/editable as, say, YAML.

**Comment by Math-ias** [comment]
I'm plain loading it from the settings.py in the django project. This is a better solution.

In the future we might have a settings.py or something like that, instead of ungracefully doing it from **init**.py.

**Comment by Math-ias** [comment]
Disregard my last pull request, the new one is better and much improved!
